[google]
type = "service_account"
project_id = "crawler-458520"
private_key_id = "10e5e370ddf487b6ef2085e85eb57809ca7490fb"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEzZOkdxq8mH2+
BhvBNK6w/3S50b3Ec5gMqAY9Jjs3DOiwodfj44k0TCIoX2/Xf4hhE+QSouwW9ja0
P4c+k0ZWRaSHjCp6SUfq78HLVA42KOI1UeAqug2ckL7p0NTkUAEGv6Cw0tNWyiRS
xBIchBORa5uX/Mei0d6O1msa/fK8t/aOnLtFlqctl0vIcGWrOdEFI7yqMXLPw2z7
Vg3A35C+0PJxftE+Q5FQBRuH9BTGvA+4J20uaKrnTzq2Bfl+DcFCTHYzrMrdX6sL
iT9EECzUnHWvTJp+Mvq9Dk3b2u08FGP9YwLh5ginQRMWJnJRot6IYXO0oefWFsSS
BR7/erYbAgMBAAECggEAR30/8SHc4f5oyuLQKTZYcO5S+f8hNqAg7xQINCVTpFM5
oZQg5uTsHcW8MLs+VuM6aL0/f6+UIGEvDPn4yHfaOJOSyTRW59X/3G1ckd5GTVE7
ns/PpOWx9Ro1Z50XAJq5TLjGiAUFhUTnvfMAe0BVFWGoAyVtZY1kEbH89TCjgP6U
8AvkAR9oGj06kRlA0GCwW949BwCN66fRBi1pZ0CQVWkbJg68pP7Gd0/cLXujc/1k
DuacMBQtZB43z+TenNiNw9nPdBkEwGrgFamIxVUUnzFIEz1OsQ7AdVlC6kTyRhVY
eLIPp79p6gLlIpXZYgdpGK2VCTb37xUPu6xO4ohXwQKBgQDye8HryICARQcMMTPd
usNyfZkI/qdxsrCo5KfncRriVGaZiTzcAJMPzuq/9OGF86JoZG4Zq3QQdQ9ky6cT
PBCGtWKMq6ZL9D0gD7SLIpfmnJ62xEK7U6toW+asMrYBgEAJfiJGcp7LZLjt1A4J
CB/0Ut67LvVZAeDgjjq/HSr62wKBgQDPxfWR2EVJdRs83HwUNy6ORLbGj6eb9FOF
U57LAMTfuxv8pEEtGiql/VKEbD/bbiIW0JcXiFmI42PEy4GvvyPzTLce7ZzbNn+o
AbNwVmvGJKhd1iVijV1HVKgzhkBEJGY6SlGvWvLDtcRV/36bMeCxkfHT4CL+cAV9
5Jg1oAD1wQKBgG6Dgv1gM1jCnRSsdBQRY7SRk6bq0QvbwfInzHKKNROEHgLJ7ofi
ZyQkTQ9Rn1t6j8F+TEO8xbgecfahbrMwg+OxVYoBTVh+p0Euhz2Gda6wIRHxXuyb
lJqKkBZZQmRqvETXTO3InaDbdgFGzWLGZjHndwXewAlh9sjBafriY01TAoGAfO0t
G1UrS+Cy0ORNYqZPQtGECF2lzLqaYWcG6k57EX7idASa/7BlBksLi32+44QT0R34
Svj7xLfcbB5kyrQlvIta66i5EIFzPiRPrPL5eDjgVxOEhP40oMgBHoHRMGemY9P9
y27m2s/2zjKCAHR8Aqia++cfg1b9plWFQ3ECQsECgYEAoQkyY8dlCmcdq1avE7wl
RxfKIXn9HYHF2HUWkHgJe21B9gkzPEc1ZwlkUPf1rcHHo/0gxI35bIxrEHzj4+EX
RdceDQGfDqONzMoBO/+xLm4/2CCyz2S0hkBpKBCdDPiVptV+ARjGuMcrD/aMp+k/
TgJJk49F0/hYgtw6vtkr1LM=
-----END PRIVATE KEY-----"""
client_email = "crawler-sheet@crawler-458520.iam.gserviceaccount.com"
client_id = "112655504969443723589"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/crawler-sheet%40crawler-458520.iam.gserviceaccount.com"

[sheets]
open = "https://docs.google.com/spreadsheets/d/1hfmS2Bf3KpmJ9mjM6idJZaKinozSqO8CNB7qfX0WlRM/edit?gid=0#gid=0"
form = "https://docs.google.com/spreadsheets/d/1_3q3I-OtNBvJx1VmaTug9Hqn_WZYIsbXQ4dVNLFrr20/edit?gid=0#gid=0"

